const canvas = document.getElementById("canvas1");
const ctx = canvas.getContext("2d");
canvas.width = window.innerWidth; // canvas size set as entire browser window
canvas.height = window.innerHeight;

let particleArray = [];
let adjustX = 10;
let adjustY = 10;

// handle mouse coordinates
const mouse = {
	x: null,
	y: null,
	radius: 50, // size of the circular area around the mouse which will react with the particles
};
window.addEventListener("mousemove", function (event) {
	// extracting x & y to the mouse object so that the coordinates are accessible globally
	mouse.x = event.x;
	mouse.y = event.y;
});

ctx.fillStyle = "white"; // fill the drawing with selected colour
ctx.font = "30px Verdane";
ctx.fillText("YN", 0, 30); // text, x, y, (max pixel in text)
// ctx.strokeStyle = "white";
// ctx.strokeRect(0, 0, 100, 100);
const textCoordinates = ctx.getImageData(0, 0, 200, 200); // get object representing the underlying pixel data for a specified portion of the canvas (x-axis, y-axis, width, height)

class Particle {
	// runs only once to create a blue print of particle
	constructor(x, y) {
		this.x = x;
		this.y = y;
		this.size = 1; // radius of each particle
		this.baseX = this.x; // hold initial coordinates of the particle
		this.baseY = this.y;
		this.density = Math.random() * 30 + 1; // 1 - 30, determines how heavy the particles are and how fast it moves away from mouse
	}

	// draw particles
	draw() {
		ctx.fillStyle = "white";
		ctx.beginPath();
		ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2); // add a circular arc (x, y, radius, startAngle, endAngle)
		ctx.closePath();
		ctx.fill();
	}

	// calculate distance between mouse and particles
	update() {
		let dx = mouse.x - this.x;
		let dy = mouse.y - this.y;
		// distance between mouse and particle ()= hypotenuse　直径三角形の斜辺)
		let distance = Math.sqrt(dx * dx + dy * dy); // Math.sqrt calculates returns the square root of a number

		let forceDirectionX = dx / distance;
		let forceDirectionY = dy / distance;

		let maxDistance = mouse.radius; // to be converted to a range of 1 to 0 so that it can be used to move particles in proportions to its current distance from the mouse
		let force = (maxDistance - distance) / maxDistance; // calculates which proportion of max distance it is (from a range of 1 to 0) so that particle slows down as it moves closer to the mouse

		// combine all factors that play a role in particle's movement
		let directionX = forceDirectionX * force * this.density;
		let directionY = forceDirectionY * force * this.density;

		if (distance < mouse.radius) {
			// as particles move away from mouse, they change as directed by directionX & Y
			this.x -= directionX; // - : move away, + : move forwards
			this.y -= directionY;
		} else {
			// once mouse moves far enough from particle, they move back to its original location
			if (this.x != this.baseX) {
				let dx = this.x - this.baseX; // distance between moved particle and its initial location
				this.x -= dx / 5; // everytime the func runs, each particle moves closer to where it initially was
			}
			if (this.y != this.baseY) {
				let dy = this.y - this.baseY;
				this.y -= dy / 5; // dividing by 10 makes the movement slow
			}
		}
	}
}

function init() {
	particleArray = [];

	// getImageData will have properties that are automatically generated by calling getImageData method, such as height, width, and data
	// inside data array, there are 4 items which represents each row x column pixel item, 1-red, 2-green, 3-blue, 4-opacity (the same say rgb color)

	// generate particles only if they're inside the pixel that we set ealier

	// analyze pixel row by row
	for (let y = 0, y2 = textCoordinates.height; y < y2; y++) {
		// for each row, alalyze each pixel from 1 to 100
		for (let x = 0, x2 = textCoordinates.width; x < x2; x++) {
			// take every 4th item in an array so that we can check only the opaicty value
			let num = y * 4 * textCoordinates.width + x * 4 + 3;
			if (textCoordinates.data[num] > 128) {
				// halfway between 0 to 255 (the same say rgb color) - 128 is roughly 0.5 of opacity
				// if opacity is more than 0.5 - can be seen on the screen
				let positionX = x + adjustX; // adjustX will let us move the letter (data points within the data)
				let positionY = y + adjustY;
				// filter out pixels that have less than 50% of opacity and leave only pixels which has data points (meaning with opacity 1)
				particleArray.push(new Particle(positionX * 10, positionY * 10));
			}
		}
	}

	// generate particles randomly
	// for (let i = 0; i < 1000; i++) {
	// 	let x = Math.random() * canvas.width; // 1 - max width of the canvas
	// 	let y = Math.random() * canvas.height; // 1 - max height of the canvas
	// 	particleArray.push(new Particle(x, y)); // call constructor of its associated class
	// }
}

init();
console.log(particleArray);

function animate() {
	ctx.clearRect(0, 0, canvas.width, canvas.height);
	for (let i = 0; i < particleArray.length; i++) {
		particleArray[i].draw();
		particleArray[i].update();
	}
	requestAnimationFrame(animate); // it tells browser to call the animate func before repaint and create a loop
}

animate();
